@startuml

class Usuario {
    prendas: Prenda[]
    borradores: Prenda[]
    atuendos: Atuendo[]
    institucion: Institucion
    --
    CrearBorrador(Tipo)
}

class Atuendo {
    prendas: Prenda[]
}

class Prenda {
    tipo: TipoDePrenda
    material: Material
    trama: Trama
    colorPrincial: Color
    colorSecuandario: Color
    --
    Categoria()
}

class PrendaBorrador {
    tipo: TipoDePrenda
    material: Material
    trama: Trama
    colorPrincial: Color
    colorSecuandario: Color
    --
    setTipo(Tipo)
    setMaterial(Material)
    setTrama(Trama)
    setColorPrincipal(Color)
    setColorSecundario(Color)
    crearPrenda()
}

class TipoDePrenda {
    descripcion: String
}

enum Trama {
    LISA
    RAYADA
    LUNARES
    CUADROS
    ESTAMPADO
}

enum Color {
    BLANCO
    NEGRO
    GRIS
    ROJO
    NARANJA
    AMARILLO
    VERDE
    AZUL
    CELESTE
    VIOLETA
    ROSA
}

enum Categoria {
    PARTE_SUPERIOR
    CALZADO
    PARTE_INFERIOR
    ACCESORIOS
}

enum Material {
    ALGODON
    LANA
    JEAN
    CUERO
}

Atuendo -->"*" Prenda

Usuario -->"*" Prenda
Usuario --> PrendaBorrador
Usuario -->"*" Atuendo

PrendaBorrador ..> Prenda

Prenda -l-> Tipo
Prenda --> Trama
Prenda -> Color
Prenda --> Material

Tipo --> Categoria

@enduml