@startuml

class Usuario {
    edad: int
    prendas: Prenda[]
    --
    guardarBorrador(PrendaBorrador)
    sugerirAtuendos()
}

class Atuendo {
    prendas: Prenda[]
}

class Prenda {
    tipo: TipoDePrenda
    material: Material
    trama: Trama
    colorPrincial: Color
    colorSecuandario: Color
    --
    Categoria()
}

class PrendaBorrador {
    tipo: TipoDePrenda
    material: Material
    trama: Trama
    colorPrincial: Color
    colorSecuandario: Color
    --
    setTipo(Tipo)
    setMaterial(Material)
    setTrama(Trama)
    setColorPrincipal(Color)
    setColorSecundario(Color)
    crearPrenda()
}

class TipoDePrenda {
    descripcion: String
}

class ProveedorDeMotores {
    MotorDeSugerencias
}

interface MotorDeSugerencias {
    sugerirAtuendos(Prenda[], Usuario)
}

class MotorDeSugerenciasEstandar {
    sugerirAtuendos(Prenda[], Usuario)
}

class MotorDeSugerenciasFormales {
    sugerirAtuendos(Prenda[], Usuario)
}

enum Trama {
    LISA
    RAYADA
    LUNARES
    CUADROS
    ESTAMPADO
}

enum Color {
    BLANCO
    NEGRO
    GRIS
    ROJO
    NARANJA
    AMARILLO
    VERDE
    AZUL
    CELESTE
    VIOLETA
    ROSA
}

enum Categoria {
    PARTE_SUPERIOR
    CALZADO
    PARTE_INFERIOR
    ACCESORIOS
}

enum Material {
    ALGODON
    LANA
    JEAN
    CUERO
}

Atuendo -->"*" Prenda

Usuario -->"*" Prenda
Usuario --> PrendaBorrador
Usuario -->"*" Atuendo
Usuario .l.> ProveedorDeMotores

PrendaBorrador ..> Prenda

Prenda -l-> TipoDePrenda
Prenda --> Trama
Prenda -> Color
Prenda --> Material

TipoDePrenda --> Categoria

ProveedorDeMotores -l-> MotorDeSugerencias

MotorDeSugerenciasEstandar -u-|> MotorDeSugerencias
MotorDeSugerenciasEstandar .r.> Atuendo

MotorDeSugerenciasFormales .u.|> MotorDeSugerenciasEstandar
MotorDeSugerenciasFormales .r.> Atuendo


@enduml