@startuml

class Usuario {
    - edad: int
    - ciudad: String
    - prendas: Prenda[]
    - motorDeSugerencias: MotorDeSugerencias
    --
    + guardarBorrador(PrendaBorrador)
    + sugerirAtuendos()
}

class Atuendo {
    prendas: Prenda[]
}

class Prenda {
    - tipo: TipoDePrenda
    - material: Material
    - trama: Trama
    - formalidad: Formalidad
    - colorPrincial: Color
    - colorSecuandario: Color
    --
    + Categoria()
    + esDeCategoria(Categoria categoria)
    + esDeFormalidad(Formalidad formalidad)
    + esParaTemperatura(double temperatura)
}

class PrendaBorrador {
    - tipo: TipoDePrenda
    - material: Material
    - trama: Trama
    - colorPrincial: Color
    - colorSecuandario: Color
    --
    + setTipo(Tipo)
    + setMaterial(Material)
    + setTrama(Trama)
    + setColorPrincipal(Color)
    + setColorSecundario(Color)
    + crearPrenda()
}

class TipoDePrenda {
    - descripcion: String
    - temperaturaDeUso: RangoDeTemperaturas
    --
    + esParaTemperatura(double temperatura)
}

class MotorDeSugerencias {
    - servicioMeteorologico
    --
    + sugerirAtuendos(Prenda[], Usuario)
}

class MotorDeSugerenciasFormales {
    + sugerirAtuendos(Prenda[], Usuario)
}

class RangoDeTemperaturas {
    - temperaturaMayor: double
    - temperaturaMenor: double
    --
    + contiene(double temperatura)
}

interface ServicioMeteorologico {
    + getTemperatura(String ciudad)
}

class ServicioMeteorologicoAccuWeather {
    - api
    - ultimasRespuestas
    - llamadosDiarios
    --
    + getTemperatura(String ciudad);
}

class RespuestaDeClima {
    - limiteExpiracion
    - respuesta
    --
    + getTemperatura()
    + expiro()
}

enum Trama {
    LISA
    RAYADA
    LUNARES
    CUADROS
    ESTAMPADO
}

enum Color {
    BLANCO
    NEGRO
    GRIS
    ROJO
    NARANJA
    AMARILLO
    VERDE
    AZUL
    CELESTE
    VIOLETA
    ROSA
}

enum Categoria {
    PARTE_SUPERIOR
    CALZADO
    PARTE_INFERIOR
    ACCESORIOS
}

enum Material {
    ALGODON
    LANA
    JEAN
    CUERO
}

enum Formalidad {
    FORMAL
    NEUTRO
    INFORMAL
}

Atuendo -->"*" Prenda
Atuendo -[hidden]r- PrendaBorrador

Usuario -->"*" Prenda
Usuario --> PrendaBorrador
Usuario -->"*" Atuendo
Usuario -l-> MotorDeSugerencias

PrendaBorrador ..> Prenda

Prenda -l-> TipoDePrenda
Prenda --> Material
Prenda --> Trama
Prenda --> Formalidad
Prenda -> Color

TipoDePrenda --> Categoria
TipoDePrenda -l-> RangoDeTemperaturas

MotorDeSugerencias .r.> Atuendo
MotorDeSugerencias -l-> ServicioMeteorologico

MotorDeSugerenciasFormales -u-|> MotorDeSugerencias

ServicioMeteorologicoAccuWeather .u.|> ServicioMeteorologico
ServicioMeteorologicoAccuWeather -u->"*" RespuestaDeClima

@enduml